/* AUTO-GENERATED by scripts/build-products.js — DO NOT EDIT BY HAND.
   Source:  data/products.json
   Command: npm run build:products
   Built:   2026-04-20T13:18:16.135Z */

(function () {
  var ADDITIONS = {};
  var MATCH_ADDITIONS = [];
  var CARDS_BY_SECTOR = {};
  var SECTOR_GRID = {
    "k-security": "productGrid",
    "k-tech":     "ktechGrid",
    "k-energy":   "kenergyGrid",
    "k-bio":      "kbioGrid"
  };

  /* Merge into the lexical `P` binding declared in index.html (const P at
     script scope is shared across classic scripts via the global lexical
     environment, but NOT exposed on window). `typeof` is safe on undeclared
     identifiers, so the guard works on pages without an inline P. */
  try {
    if (typeof P !== "undefined" && P && typeof P === "object") {
      Object.keys(ADDITIONS).forEach(function (id) {
        if (!P[id]) P[id] = ADDITIONS[id];
      });
    }
  } catch (_) {}
  try {
    if (typeof MATCH_CATALOG !== "undefined" && Array.isArray(MATCH_CATALOG)) {
      MATCH_ADDITIONS.forEach(function (m) {
        if (!MATCH_CATALOG.some(function (x) { return x.id === m.id; })) {
          MATCH_CATALOG.push(m);
        }
      });
    }
  } catch (_) {}

  /* Also expose on window — standalone pages' chat-core.js reads window.P. */
  if (!window.P) window.P = {};
  Object.keys(ADDITIONS).forEach(function (id) {
    if (!window.P[id]) window.P[id] = ADDITIONS[id];
  });
  if (Array.isArray(window.MATCH_CATALOG)) {
    MATCH_ADDITIONS.forEach(function (m) {
      if (!window.MATCH_CATALOG.some(function (x) { return x.id === m.id; })) {
        window.MATCH_CATALOG.push(m);
      }
    });
  }

  /* Runtime card builder — mirrors index.html card markup byte-for-byte. */
  var cardHtmlFor = function cardHtmlFor(id, p, i) {
    /* Mirrors index.html's inline card markup so the style matches 1:1. */
    const tag  = (p.cardTag || p.sub || '').replace(/"/g, '&quot;');
    const mfg  = (p.maker || 'ERGSN CO., LTD.') + ' <span class="card-verified">\u2713 Verified Partner</span>';
    const miniSpecs = (p.specs || []).slice(0, 4)
      .map(([k, v]) => `<div><p class="spec-lbl">${k}</p><p class="spec-val">${v}</p></div>`)
      .join('');
    const imgBlock = p.img
      ? `<div class="card-image"><picture><source srcset="${p.img.replace(/\.jpg$|\.png$/, '.webp')}" type="image/webp"><img src="${p.img}" alt="ERGSN ${p.model}" loading="lazy"></picture></div>`
      : '';
    const cardHtml =
      `<div class="product-card reveal" style="--i:${i}" tabindex="0" data-model="${id}" onclick="openModal('${id}')" onkeydown="if(event.key==='Enter'&&event.target===this)openModal('${id}')">` +
        imgBlock +
        `<p class="card-tag">${tag}</p>` +
        `<p class="card-model">${p.model}</p>` +
        `<p class="card-part">Part No: ${p.part}</p>` +
        `<p class="card-mfg">${mfg}</p>` +
        `<p class="card-desc">${p.desc.split('. ')[0]}.</p>` +
        `<div class="card-specs">${miniSpecs}</div>` +
        `<div class="card-foot">` +
          `<span class="card-cta">View Full Specs</span>` +
          `<button class="compare-btn" type="button" aria-label="Add ${p.model} to compare" onclick="event.stopPropagation();toggleCompare('${id}',this)">` +
            `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"><path d="M6 12h12M12 6v12"/></svg>Compare` +
          `</button>` +
        `</div>` +
      `</div>`;
    return cardHtml;
  };

  function injectCards() {
    Object.keys(CARDS_BY_SECTOR).forEach(function (sector) {
      var gridId = SECTOR_GRID[sector];
      if (!gridId) return; /* sector not active — skip for now */
      var grid = document.getElementById(gridId);
      if (!grid) return;
      var existing = Array.prototype.map.call(grid.querySelectorAll(":scope > .product-card"), function (c) { return c.getAttribute("data-model"); });
      CARDS_BY_SECTOR[sector].forEach(function (p, i) {
        if (existing.indexOf(p.id) !== -1) return; /* already rendered inline */
        var tmp = document.createElement("div");
        tmp.innerHTML = cardHtmlFor(p.id, ADDITIONS[p.id], i);
        grid.appendChild(tmp.firstChild);
      });
    });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", injectCards);
  } else {
    injectCards();
  }
})();
