/* AUTO-GENERATED by scripts/build-products.js — DO NOT EDIT BY HAND.
   Source:  data/products.json
   Command: npm run build:products
   Built:   2026-04-23T09:07:51.636Z */

(function () {
  var ADDITIONS = {
  "ddell-dewy-glow-cushion": {
    "model": "DEWY GLOW CUSHION PACT",
    "sub": "DD'ELL · Dewy-finish cushion foundation for hydrated glow",
    "part": "DDELL-CUSH-DG (PRD-955)",
    "specs": [
      [
        "Brand",
        "DD'ELL"
      ],
      [
        "Category",
        "Makeup — Cushion Pact"
      ],
      [
        "Finish",
        "Dewy / Luminous"
      ],
      [
        "Retail MSRP",
        "USD 36"
      ],
      [
        "Manufacturer",
        "COSMEDIQUE Co., Ltd."
      ]
    ],
    "features": [
      "Dewy luminous finish — ideal for normal-to-dry skin",
      "Hydrating formula with buildable coverage",
      "OEM/ODM custom shade and packaging available",
      "Korean-manufactured under COSMEDIQUE since 1985"
    ],
    "desc": "Long-wear dewy-finish cushion foundation from DD'ELL, manufactured by COSMEDIQUE Co., Ltd. Buildable coverage, hydrating formula suitable for normal-to-dry skin. OEM/ODM-ready — custom shades and packaging available at MOQ 1,000 per SKU.",
    "img": "images/products/ddell-dewy-glow-cushion.jpg"
  },
  "ddell-line-lift-cushion": {
    "model": "LINE LIFT CUSHION PACT",
    "sub": "DD'ELL · Lifting cushion with firming peptide complex",
    "part": "DDELL-CUSH-LL (PRD-954)",
    "specs": [
      [
        "Brand",
        "DD'ELL"
      ],
      [
        "Category",
        "Makeup — Cushion Pact"
      ],
      [
        "Finish",
        "Semi-matte / Lifting"
      ],
      [
        "Retail MSRP",
        "USD 36"
      ],
      [
        "Manufacturer",
        "COSMEDIQUE Co., Ltd."
      ]
    ],
    "features": [
      "Peptide-enhanced lifting formula",
      "Buildable coverage with semi-matte finish",
      "CGMP-compliant Korean manufacturing",
      "OEM/ODM private-label ready at MOQ 1,000"
    ],
    "desc": "Firming line-lift cushion foundation from DD'ELL. Combines peptide complex with buildable coverage for a sculpted, age-defying finish. Manufactured by COSMEDIQUE Co., Ltd. under Korean cosmetic safety standards (CGMP).",
    "img": "images/products/ddell-line-lift-cushion.jpg"
  },
  "ddell-filter-primer-zeropore": {
    "model": "FILTER PRIMER ZEROPORE",
    "sub": "DD'ELL · Pore-blurring primer with smoothing silicone matrix",
    "part": "DDELL-PRIM-ZP (PRD-964)",
    "specs": [
      [
        "Brand",
        "DD'ELL"
      ],
      [
        "Category",
        "Makeup — Primer / Base"
      ],
      [
        "Texture",
        "Silicone gel-cream"
      ],
      [
        "Retail MSRP",
        "USD 26"
      ],
      [
        "Manufacturer",
        "COSMEDIQUE Co., Ltd."
      ]
    ],
    "features": [
      "Instant pore-blurring optical effect",
      "Silicone matrix for smooth foundation application",
      "Oil-control for long-wear makeup",
      "OEM/ODM-ready at MOQ 1,000 per SKU"
    ],
    "desc": "Makeup primer designed to blur pores and create a smooth canvas for foundation. Silicone-based matrix delivers immediate pore-filling effect. From DD'ELL, made by COSMEDIQUE Co., Ltd.",
    "img": "images/products/ddell-filter-primer-zeropore.jpg"
  },
  "ddell-setup-creame": {
    "model": "SETUP CREAME",
    "sub": "DD'ELL · Hydrating makeup-base cream for lasting wear",
    "part": "DDELL-CRM-SU (PRD-956)",
    "specs": [
      [
        "Brand",
        "DD'ELL"
      ],
      [
        "Category",
        "Makeup Base / Moisturizer"
      ],
      [
        "Texture",
        "Rich cream"
      ],
      [
        "Retail MSRP",
        "USD 28"
      ],
      [
        "Manufacturer",
        "COSMEDIQUE Co., Ltd."
      ]
    ],
    "features": [
      "Deep hydration — improves foundation adhesion",
      "Extends long-wear performance of makeup",
      "Suitable for normal-to-dry skin",
      "OEM/ODM customisation at MOQ 1,000"
    ],
    "desc": "Rich hydrating cream designed as a makeup base — locks moisture, improves foundation adhesion, and extends wear time. Manufactured by COSMEDIQUE Co., Ltd. under Korean CGMP standards.",
    "img": "images/products/ddell-setup-creame.jpg"
  },
  "ddell-glowup-cream": {
    "model": "GLOWUP CREAM",
    "sub": "DD'ELL · Radiance-boosting cream with luminous pigment complex",
    "part": "DDELL-CRM-GU (PRD-958)",
    "specs": [
      [
        "Brand",
        "DD'ELL"
      ],
      [
        "Category",
        "Skincare / Glow Cream"
      ],
      [
        "Texture",
        "Lightweight cream"
      ],
      [
        "Retail MSRP",
        "USD 28"
      ],
      [
        "Manufacturer",
        "COSMEDIQUE Co., Ltd."
      ]
    ],
    "features": [
      "Light-reflecting radiance complex",
      "Hydration + subtle luminous finish in one step",
      "Works solo or as makeup primer",
      "OEM/ODM-ready with private-label packaging"
    ],
    "desc": "Daily-wear radiance cream from DD'ELL that delivers an immediate luminous finish. Blends skincare hydration with a subtle light-reflecting pigment complex for a healthy-glow look, on its own or under makeup.",
    "img": "images/products/ddell-glowup-cream.jpg"
  },
  "ddell-mask-defense": {
    "model": "MAKEUP FIXER MASK DEFENSE",
    "sub": "DD'ELL · Setting mist engineered for mask-on makeup wear",
    "part": "DDELL-FIX-MD (PRD-961)",
    "specs": [
      [
        "Brand",
        "DD'ELL"
      ],
      [
        "Category",
        "Makeup Fixer / Setting Mist"
      ],
      [
        "Format",
        "Pump mist spray"
      ],
      [
        "Retail MSRP",
        "USD 16"
      ],
      [
        "Manufacturer",
        "COSMEDIQUE Co., Ltd."
      ]
    ],
    "features": [
      "Mask-proof makeup lock technology",
      "Non-sticky, quick-dry finish",
      "Anti-transfer and anti-oxidation",
      "OEM/ODM with private-label fragrance options"
    ],
    "desc": "Setting mist specifically formulated to keep makeup intact under face masks. Quick-drying, non-sticky finish — prevents transfer and oxidation during extended wear. From DD'ELL, by COSMEDIQUE Co., Ltd.",
    "img": "images/products/ddell-mask-defense.jpg"
  },
  "ddell-fixer-dewy-glow": {
    "model": "MAKEUP FIXER DEWY GLOW",
    "sub": "DD'ELL · Setting mist that locks in a dewy, luminous finish",
    "part": "DDELL-FIX-DG (PRD-959)",
    "specs": [
      [
        "Brand",
        "DD'ELL"
      ],
      [
        "Category",
        "Makeup Fixer / Setting Mist"
      ],
      [
        "Finish",
        "Dewy / Luminous"
      ],
      [
        "Retail MSRP",
        "USD 16"
      ],
      [
        "Manufacturer",
        "COSMEDIQUE Co., Ltd."
      ]
    ],
    "features": [
      "Locks in a dewy glow finish",
      "Alcohol-free formulation — no tight-feel",
      "Fine micro-mist atomiser",
      "OEM/ODM options for volume and scent"
    ],
    "desc": "Setting mist from DD'ELL that finishes makeup with a dewy, hydrated glow. Fine-atomising pump delivers an even micro-mist with no alcohol drag. Made by COSMEDIQUE Co., Ltd. in Seoul.",
    "img": "images/products/ddell-fixer-dewy-glow.jpg"
  },
  "ddell-egf-ampoule": {
    "model": "E.G.F AMPOULE",
    "sub": "DD'ELL · Epidermal Growth Factor ampoule for advanced skin repair",
    "part": "DDELL-AMP-EGF (PRD-909)",
    "specs": [
      [
        "Brand",
        "DD'ELL"
      ],
      [
        "Category",
        "Skincare / Advanced Ampoule"
      ],
      [
        "Key Actives",
        "Epidermal Growth Factor (EGF)"
      ],
      [
        "Retail MSRP",
        "USD 76"
      ],
      [
        "Manufacturer",
        "COSMEDIQUE Co., Ltd."
      ]
    ],
    "features": [
      "High-potency EGF for cellular renewal",
      "Barrier repair and fine-line reduction",
      "Dermatologically tested formulation",
      "OEM/ODM available with MOQ 1,000"
    ],
    "desc": "High-concentration EGF (Epidermal Growth Factor) ampoule from DD'ELL. Targets cellular turnover, skin barrier repair, and fine-line reduction. Manufactured by COSMEDIQUE Co., Ltd. — a biomedical cosmetic specialist.",
    "img": "images/products/ddell-egf-ampoule.jpg"
  },
  "demed-vitamin-c-ampoule": {
    "model": "VITAMIN C AMPOULE",
    "sub": "DEMED · Brightening ampoule with fast-absorbing Vitamin C",
    "part": "DEMED-AMP-VC (PRD-81)",
    "specs": [
      [
        "Brand",
        "DEMED (est. 1985)"
      ],
      [
        "Category",
        "Dermatological Ampoule"
      ],
      [
        "Volume",
        "7 ml × 5 EA"
      ],
      [
        "Key Actives",
        "Vitamin C (Ascorbyl derivatives)"
      ],
      [
        "Retail MSRP",
        "USD 133.20"
      ],
      [
        "Manufacturer",
        "COSMEDIQUE Co., Ltd."
      ]
    ],
    "features": [
      "Brightening — targets dullness and pigmentation",
      "Fast-absorbing ampoule format for daily intensive care",
      "Sealed single-use vials preserve ingredient stability",
      "OEM/ODM available at MOQ 1,000 per SKU"
    ],
    "desc": "Dermatological Vitamin C brightening ampoule from DEMED (est. 1985). 7ml × 5 ampoules format; fast-absorbing formula targets dull tone, pigmentation, and uneven texture. Manufactured by COSMEDIQUE Co., Ltd. under 39+ years of Korean cosmetic R&D.",
    "img": "images/products/demed-vitamin-c-ampoule.jpg"
  },
  "demed-collagen-ampoule-30ml": {
    "model": "COLLAGEN AMPOULE 30ML",
    "sub": "DEMED · Firming collagen ampoule in 30 ml jumbo format",
    "part": "DEMED-AMP-COL30 (PRD-65)",
    "specs": [
      [
        "Brand",
        "DEMED (est. 1985)"
      ],
      [
        "Category",
        "Dermatological Ampoule"
      ],
      [
        "Volume",
        "30 ml"
      ],
      [
        "Key Actives",
        "Hydrolysed collagen peptides"
      ],
      [
        "Retail MSRP",
        "USD 57.72"
      ],
      [
        "Manufacturer",
        "COSMEDIQUE Co., Ltd."
      ]
    ],
    "features": [
      "Firming and elasticity support via collagen peptides",
      "Large 30 ml format — daily face + neck use",
      "Lightweight, fast-absorbing texture",
      "OEM/ODM-ready with custom packaging"
    ],
    "desc": "High-concentration collagen ampoule in a generous 30 ml pump bottle — suitable for daily face + neck application. From DEMED (1985), a dermatological cosmetic brand manufactured by COSMEDIQUE Co., Ltd.",
    "img": "images/products/demed-collagen-ampoule-30ml.jpg"
  },
  "demed-collagen-ampoule-7ml": {
    "model": "COLLAGEN AMPOULE 7ML × 5EA",
    "sub": "DEMED · Collagen ampoule in single-use vial 5-pack",
    "part": "DEMED-AMP-COL5 (PRD-82)",
    "specs": [
      [
        "Brand",
        "DEMED (est. 1985)"
      ],
      [
        "Category",
        "Dermatological Ampoule"
      ],
      [
        "Volume",
        "7 ml × 5 EA"
      ],
      [
        "Key Actives",
        "Hydrolysed collagen peptides"
      ],
      [
        "Retail MSRP",
        "USD 133.20"
      ],
      [
        "Manufacturer",
        "COSMEDIQUE Co., Ltd."
      ]
    ],
    "features": [
      "Intensive single-use 5-pack treatment",
      "Sealed vials preserve peptide freshness",
      "Firming and elasticity support",
      "OEM/ODM with private-label vial branding"
    ],
    "desc": "5-pack of single-use 7 ml collagen ampoules for intensive weekly treatment. Sealed vials preserve peptide integrity. Manufactured by COSMEDIQUE Co., Ltd. — premium dermatological cosmetics since 1985.",
    "img": "images/products/demed-collagen-ampoule-7ml.jpg"
  },
  "demed-hyaluronic-soothing-ampoule": {
    "model": "HYALURONIC SOOTHING AMPOULE",
    "sub": "DEMED · Multi-weight hyaluronic soothing ampoule, 7 ml × 5",
    "part": "DEMED-AMP-HYA (PRD-60)",
    "specs": [
      [
        "Brand",
        "DEMED (est. 1985)"
      ],
      [
        "Category",
        "Dermatological Ampoule"
      ],
      [
        "Volume",
        "7 ml × 5 EA"
      ],
      [
        "Key Actives",
        "Multi-weight Hyaluronic Acid"
      ],
      [
        "Retail MSRP",
        "USD 125.80"
      ],
      [
        "Manufacturer",
        "COSMEDIQUE Co., Ltd."
      ]
    ],
    "features": [
      "Layered hydration with multi-weight HA",
      "Soothing for sensitised and post-procedure skin",
      "Moisture-barrier repair",
      "OEM/ODM-ready at MOQ 1,000"
    ],
    "desc": "Soothing ampoule featuring multi-molecular-weight hyaluronic acid for layered hydration. Calms sensitised skin while restoring moisture barrier. From DEMED by COSMEDIQUE Co., Ltd.",
    "img": "images/products/demed-hyaluronic-soothing-ampoule.jpg"
  },
  "demed-brightening-ampoule": {
    "model": "BRIGHTENING AMPOULE",
    "sub": "DEMED · Intensive brightening ampoule, 7 ml × 5",
    "part": "DEMED-AMP-BRT (PRD-61)",
    "specs": [
      [
        "Brand",
        "DEMED (est. 1985)"
      ],
      [
        "Category",
        "Dermatological Ampoule"
      ],
      [
        "Volume",
        "7 ml × 5 EA"
      ],
      [
        "Key Actives",
        "Niacinamide + Vitamin C complex"
      ],
      [
        "Retail MSRP",
        "USD 133.20"
      ],
      [
        "Manufacturer",
        "COSMEDIQUE Co., Ltd."
      ]
    ],
    "features": [
      "Targets melanin over-production and PIH",
      "Intensive 5-pack weekly treatment",
      "Sealed vials preserve active stability",
      "OEM/ODM with custom active concentrations"
    ],
    "desc": "Intensive brightening ampoule targeting uneven tone, melanin over-production, and post-inflammatory pigmentation. 5 single-use vials for concentrated weekly treatment. From DEMED, manufactured by COSMEDIQUE Co., Ltd.",
    "img": "images/products/demed-brightening-ampoule.jpg"
  },
  "demed-spicule-peptide-300": {
    "model": "SPICULE PEPTIDE 300 SHOT",
    "sub": "DEMED · Spicule-delivery peptide shot ampoule, 7 ml × 5",
    "part": "DEMED-AMP-SP300 (PRD-59)",
    "specs": [
      [
        "Brand",
        "DEMED (est. 1985)"
      ],
      [
        "Category",
        "Advanced Dermatological Ampoule"
      ],
      [
        "Volume",
        "7 ml × 5 EA"
      ],
      [
        "Technology",
        "Marine spicule delivery + peptides"
      ],
      [
        "Retail MSRP",
        "USD 125.80"
      ],
      [
        "Manufacturer",
        "COSMEDIQUE Co., Ltd."
      ]
    ],
    "features": [
      "Marine spicule micro-channel delivery",
      "Deep-penetration peptide complex",
      "Clinical-grade home-care formulation",
      "OEM/ODM technology licensing available"
    ],
    "desc": "Advanced spicule-technology ampoule from DEMED. Marine spicules create micro-channels that drive peptide actives deeper into the skin — clinical-grade home-care targeting fine lines and texture. Made by COSMEDIQUE Co., Ltd.",
    "img": "images/products/demed-spicule-peptide-300.jpg"
  },
  "demed-extra-intense-moisture-cream-m8": {
    "model": "EXTRA INTENSE MOISTURE CREAM 50G [M8]",
    "sub": "DEMED · Barrier-repair cream for very dry / compromised skin",
    "part": "DEMED-CRM-M8 (PRD-71)",
    "specs": [
      [
        "Brand",
        "DEMED (est. 1985)"
      ],
      [
        "Category",
        "Dermatological Moisture Cream"
      ],
      [
        "Volume",
        "50 g"
      ],
      [
        "Series",
        "M-series [M8]"
      ],
      [
        "Retail MSRP",
        "USD 72.52"
      ],
      [
        "Manufacturer",
        "COSMEDIQUE Co., Ltd."
      ]
    ],
    "features": [
      "Intensive barrier-repair formulation",
      "Ceramide + occlusive complex for very dry skin",
      "Suitable for post-procedure / compromised skin",
      "OEM/ODM formulation tiers M1–M8 available"
    ],
    "desc": "Extra-rich moisture cream from DEMED's dermatological M-series. Targets very dry, dehydrated, or post-procedure skin with barrier-repair ceramides and occlusives. 50g jar. Manufactured by COSMEDIQUE Co., Ltd.",
    "img": "images/products/demed-extra-intense-moisture-cream-m8.jpg"
  },
  "hanok-sopunghun": {
    "model": "Sopunghun",
    "sub": "Classic Hanok Stay · 25-pyeong (~83 m²)",
    "part": "YSH-SPH-25 (3 identical units · Rooms 1 · 2 · 3)",
    "specs": [
      [
        "Floor Area",
        "25 pyeong (~83 m²)"
      ],
      [
        "Capacity",
        "4 standard / 6 max"
      ],
      [
        "Units",
        "3 identical (Rooms 1·2·3)"
      ],
      [
        "Amenities",
        "Hinoki cypress room · Full kitchen · Free WiFi"
      ],
      [
        "Location",
        "Yangpyeong, Gyeonggi-do"
      ],
      [
        "Share Program",
        "Annual gujwa-bunyang fractional share"
      ]
    ],
    "features": [
      "Stand-alone 25-pyeong traditional hanok unit",
      "Hinoki cypress bath room and full kitchen",
      "Three identical units operable independently",
      "Annual fractional share (gujwa-bunyang) ownership available"
    ],
    "desc": "25-pyeong traditional stand-alone hanok unit at Yangpyeong Soohyang The Hanok — accommodates 4 standard / 6 max guests. Each unit features a hinoki cypress room, full kitchen, and free WiFi. Three identical units available (Rooms 1·2·3). Annual gujwa-bunyang fractional share ownership program offered to long-term investors."
  },
  "hanok-soyojae": {
    "model": "Soyojae",
    "sub": "Premium Hanok Stay · 30-pyeong (~99 m²)",
    "part": "YSH-SYJ-30 (3 identical units · Rooms 1 · 2 · 3)",
    "specs": [
      [
        "Floor Area",
        "30 pyeong (~99 m²)"
      ],
      [
        "Capacity",
        "4 standard / 8 max"
      ],
      [
        "Units",
        "3 identical (Rooms 1·2·3)"
      ],
      [
        "Amenities",
        "Hinoki cypress room · Full kitchen · Free WiFi"
      ],
      [
        "Location",
        "Yangpyeong, Gyeonggi-do"
      ],
      [
        "Share Program",
        "Annual gujwa-bunyang fractional share"
      ]
    ],
    "features": [
      "Premium 30-pyeong stand-alone hanok with larger footprint",
      "Hinoki cypress bath room and full kitchen",
      "Three identical units operable independently",
      "Annual fractional share (gujwa-bunyang) ownership available"
    ],
    "desc": "30-pyeong premium stand-alone hanok unit at Yangpyeong Soohyang The Hanok — accommodates 4 standard / 8 max guests. Larger footprint with hinoki cypress room, full kitchen, and free WiFi. Three identical units available (Rooms 1·2·3). Annual gujwa-bunyang fractional share ownership program offered."
  },
  "hanok-gyeonwujae": {
    "model": "Gyeonwujae",
    "sub": "Pet-Friendly Hanok · 25-pyeong (~83 m²)",
    "part": "YSH-GWJ-25P (2 identical units · Rooms 1 · 2)",
    "specs": [
      [
        "Floor Area",
        "25 pyeong (~83 m²)"
      ],
      [
        "Capacity",
        "4 standard / 6 max"
      ],
      [
        "Units",
        "2 identical (Rooms 1·2)"
      ],
      [
        "Pet Policy",
        "Dogs welcome"
      ],
      [
        "Location",
        "Yangpyeong, Gyeonggi-do"
      ],
      [
        "Share Program",
        "Annual gujwa-bunyang fractional share"
      ]
    ],
    "features": [
      "Pet-friendly 25-pyeong stand-alone hanok (dogs welcome)",
      "Hinoki cypress bath room and full kitchen",
      "Two identical units operable independently",
      "Annual fractional share (gujwa-bunyang) ownership available"
    ],
    "desc": "25-pyeong pet-friendly stand-alone hanok unit at Yangpyeong Soohyang The Hanok — dogs welcome. Accommodates 4 standard / 6 max guests with hinoki cypress room, full kitchen, and free WiFi. Two identical units available (Rooms 1·2). Annual gujwa-bunyang fractional share ownership program offered."
  },
  "hanok-punggyeonru": {
    "model": "Punggyeonru",
    "sub": "Premium Pet-Friendly Hanok · 30-pyeong (~99 m²)",
    "part": "YSH-PGR-30P (3 identical units · Rooms 1 · 2 · 3)",
    "specs": [
      [
        "Floor Area",
        "30 pyeong (~99 m²)"
      ],
      [
        "Capacity",
        "4 standard / 8 max"
      ],
      [
        "Units",
        "3 identical (Rooms 1·2·3)"
      ],
      [
        "Pet Policy",
        "Dogs welcome"
      ],
      [
        "Location",
        "Yangpyeong, Gyeonggi-do"
      ],
      [
        "Share Program",
        "Annual gujwa-bunyang fractional share"
      ]
    ],
    "features": [
      "Premium pet-friendly 30-pyeong stand-alone hanok (dogs welcome)",
      "Hinoki cypress bath room and full kitchen",
      "Three identical units operable independently",
      "Annual fractional share (gujwa-bunyang) ownership available"
    ],
    "desc": "30-pyeong premium pet-friendly stand-alone hanok unit at Yangpyeong Soohyang The Hanok — dogs welcome. Accommodates 4 standard / 8 max guests with hinoki cypress room, full kitchen, and free WiFi. Three identical units available (Rooms 1·2·3). Annual gujwa-bunyang fractional share ownership program offered."
  },
  "demed-wonder-ceramid-toner": {
    "model": "WONDER CERAMID TONER",
    "sub": "DEMED · New-release ceramide toner for barrier support",
    "part": "DEMED-TNR-WC (PRD-92)",
    "specs": [
      [
        "Brand",
        "DEMED (est. 1985)"
      ],
      [
        "Category",
        "Dermatological Toner"
      ],
      [
        "Key Actives",
        "Ceramide NP complex"
      ],
      [
        "Release",
        "2024 New Release"
      ],
      [
        "Manufacturer",
        "COSMEDIQUE Co., Ltd."
      ]
    ],
    "features": [
      "Ceramide-forward barrier support",
      "First-step hydration layer",
      "Primes skin for subsequent ampoules / creams",
      "OEM/ODM-ready with custom fragrance / pH"
    ],
    "desc": "Recently-released ceramide-rich toner from DEMED. First-step hydration that primes the barrier for subsequent actives. Dermatologically formulated, manufactured by COSMEDIQUE Co., Ltd. under CGMP Korean standards.",
    "img": "images/products/demed-wonder-ceramid-toner.jpg"
  }
};
  var MATCH_ADDITIONS = [
  {
    "id": "ddell-dewy-glow-cushion",
    "name": "DEWY GLOW CUSHION PACT — DD'ELL · Dewy-finish cushion foundation for hydrated glow",
    "sector": "K-Beauty",
    "tags": [
      "retail",
      "hospitality"
    ],
    "scale": [
      "m",
      "l"
    ],
    "desc": "Dewy-finish cushion foundation · DD'ELL · MOQ 1,000",
    "coming": false
  },
  {
    "id": "ddell-line-lift-cushion",
    "name": "LINE LIFT CUSHION PACT — DD'ELL · Lifting cushion with firming peptide complex",
    "sector": "K-Beauty",
    "tags": [
      "retail",
      "hospitality"
    ],
    "scale": [
      "m",
      "l"
    ],
    "desc": "Peptide line-lift cushion · DD'ELL · MOQ 1,000",
    "coming": false
  },
  {
    "id": "ddell-filter-primer-zeropore",
    "name": "FILTER PRIMER ZEROPORE — DD'ELL · Pore-blurring primer with smoothing silicone matrix",
    "sector": "K-Beauty",
    "tags": [
      "retail",
      "hospitality"
    ],
    "scale": [
      "m",
      "l"
    ],
    "desc": "Pore-blurring makeup primer · DD'ELL · MOQ 1,000",
    "coming": false
  },
  {
    "id": "ddell-setup-creame",
    "name": "SETUP CREAME — DD'ELL · Hydrating makeup-base cream for lasting wear",
    "sector": "K-Beauty",
    "tags": [
      "retail",
      "hospitality"
    ],
    "scale": [
      "m",
      "l"
    ],
    "desc": "Hydrating makeup-base cream · DD'ELL · MOQ 1,000",
    "coming": false
  },
  {
    "id": "ddell-glowup-cream",
    "name": "GLOWUP CREAM — DD'ELL · Radiance-boosting cream with luminous pigment complex",
    "sector": "K-Beauty",
    "tags": [
      "retail",
      "hospitality"
    ],
    "scale": [
      "m",
      "l"
    ],
    "desc": "Luminous radiance cream · DD'ELL · MOQ 1,000",
    "coming": false
  },
  {
    "id": "ddell-mask-defense",
    "name": "MAKEUP FIXER MASK DEFENSE — DD'ELL · Setting mist engineered for mask-on makeup wear",
    "sector": "K-Beauty",
    "tags": [
      "retail",
      "hospitality"
    ],
    "scale": [
      "m",
      "l"
    ],
    "desc": "Mask-proof setting mist · DD'ELL · MOQ 1,000",
    "coming": false
  },
  {
    "id": "ddell-fixer-dewy-glow",
    "name": "MAKEUP FIXER DEWY GLOW — DD'ELL · Setting mist that locks in a dewy, luminous finish",
    "sector": "K-Beauty",
    "tags": [
      "retail",
      "hospitality"
    ],
    "scale": [
      "m",
      "l"
    ],
    "desc": "Dewy-glow setting mist · DD'ELL · MOQ 1,000",
    "coming": false
  },
  {
    "id": "ddell-egf-ampoule",
    "name": "E.G.F AMPOULE — DD'ELL · Epidermal Growth Factor ampoule for advanced skin repair",
    "sector": "K-Beauty",
    "tags": [
      "retail",
      "healthcare",
      "hospitality"
    ],
    "scale": [
      "m",
      "l"
    ],
    "desc": "EGF repair ampoule · DD'ELL · MOQ 1,000",
    "coming": false
  },
  {
    "id": "demed-vitamin-c-ampoule",
    "name": "VITAMIN C AMPOULE — DEMED · Brightening ampoule with fast-absorbing Vitamin C",
    "sector": "K-Beauty",
    "tags": [
      "retail",
      "healthcare",
      "hospitality"
    ],
    "scale": [
      "m",
      "l"
    ],
    "desc": "Vitamin C brightening ampoule · DEMED · MOQ 1,000",
    "coming": false
  },
  {
    "id": "demed-collagen-ampoule-30ml",
    "name": "COLLAGEN AMPOULE 30ML — DEMED · Firming collagen ampoule in 30 ml jumbo format",
    "sector": "K-Beauty",
    "tags": [
      "retail",
      "healthcare",
      "hospitality"
    ],
    "scale": [
      "m",
      "l"
    ],
    "desc": "Collagen firming ampoule 30 ml · DEMED · MOQ 1,000",
    "coming": false
  },
  {
    "id": "demed-collagen-ampoule-7ml",
    "name": "COLLAGEN AMPOULE 7ML × 5EA — DEMED · Collagen ampoule in single-use vial 5-pack",
    "sector": "K-Beauty",
    "tags": [
      "retail",
      "healthcare",
      "hospitality"
    ],
    "scale": [
      "m",
      "l"
    ],
    "desc": "Collagen ampoule 7 ml × 5 · DEMED · MOQ 1,000",
    "coming": false
  },
  {
    "id": "demed-hyaluronic-soothing-ampoule",
    "name": "HYALURONIC SOOTHING AMPOULE — DEMED · Multi-weight hyaluronic soothing ampoule, 7 ml × 5",
    "sector": "K-Beauty",
    "tags": [
      "retail",
      "healthcare",
      "hospitality"
    ],
    "scale": [
      "m",
      "l"
    ],
    "desc": "Hyaluronic soothing ampoule · DEMED · MOQ 1,000",
    "coming": false
  },
  {
    "id": "demed-brightening-ampoule",
    "name": "BRIGHTENING AMPOULE — DEMED · Intensive brightening ampoule, 7 ml × 5",
    "sector": "K-Beauty",
    "tags": [
      "retail",
      "healthcare",
      "hospitality"
    ],
    "scale": [
      "m",
      "l"
    ],
    "desc": "Brightening ampoule · DEMED · MOQ 1,000",
    "coming": false
  },
  {
    "id": "demed-spicule-peptide-300",
    "name": "SPICULE PEPTIDE 300 SHOT — DEMED · Spicule-delivery peptide shot ampoule, 7 ml × 5",
    "sector": "K-Beauty",
    "tags": [
      "retail",
      "healthcare",
      "hospitality"
    ],
    "scale": [
      "m",
      "l"
    ],
    "desc": "Spicule peptide 300 shot · DEMED · MOQ 1,000",
    "coming": false
  },
  {
    "id": "demed-extra-intense-moisture-cream-m8",
    "name": "EXTRA INTENSE MOISTURE CREAM 50G [M8] — DEMED · Barrier-repair cream for very dry / compromised skin",
    "sector": "K-Beauty",
    "tags": [
      "retail",
      "healthcare",
      "hospitality"
    ],
    "scale": [
      "m",
      "l"
    ],
    "desc": "Barrier-repair moisture cream · DEMED · MOQ 1,000",
    "coming": false
  },
  {
    "id": "hanok-sopunghun",
    "name": "Sopunghun — Classic Hanok Stay · 25-pyeong (~83 m²)",
    "sector": "K-Tourism Assets",
    "tags": [
      "hospitality"
    ],
    "scale": [
      "m",
      "l"
    ],
    "desc": "Classic 25-pyeong hanok unit · Yangpyeong · 4 std / 6 max · annual share",
    "coming": false
  },
  {
    "id": "hanok-soyojae",
    "name": "Soyojae — Premium Hanok Stay · 30-pyeong (~99 m²)",
    "sector": "K-Tourism Assets",
    "tags": [
      "hospitality"
    ],
    "scale": [
      "m",
      "l"
    ],
    "desc": "Premium 30-pyeong hanok unit · Yangpyeong · 4 std / 8 max · annual share",
    "coming": false
  },
  {
    "id": "hanok-gyeonwujae",
    "name": "Gyeonwujae — Pet-Friendly Hanok · 25-pyeong (~83 m²)",
    "sector": "K-Tourism Assets",
    "tags": [
      "hospitality"
    ],
    "scale": [
      "m",
      "l"
    ],
    "desc": "Pet-friendly 25-pyeong hanok · Yangpyeong · 4 std / 6 max · dogs welcome",
    "coming": false
  },
  {
    "id": "hanok-punggyeonru",
    "name": "Punggyeonru — Premium Pet-Friendly Hanok · 30-pyeong (~99 m²)",
    "sector": "K-Tourism Assets",
    "tags": [
      "hospitality"
    ],
    "scale": [
      "m",
      "l"
    ],
    "desc": "Premium pet-friendly 30-pyeong hanok · Yangpyeong · 4 std / 8 max · dogs welcome",
    "coming": false
  },
  {
    "id": "demed-wonder-ceramid-toner",
    "name": "WONDER CERAMID TONER — DEMED · New-release ceramide toner for barrier support",
    "sector": "K-Beauty",
    "tags": [
      "retail",
      "healthcare",
      "hospitality"
    ],
    "scale": [
      "m",
      "l"
    ],
    "desc": "Ceramide barrier toner · DEMED · MOQ 1,000",
    "coming": false
  }
];
  var CARDS_BY_SECTOR = {
  "k-beauty": [
    {
      "id": "ddell-dewy-glow-cushion",
      "sector": "k-beauty",
      "model": "DEWY GLOW CUSHION PACT",
      "part": "DDELL-CUSH-DG (PRD-955)",
      "sub": "DD'ELL · Dewy-finish cushion foundation for hydrated glow",
      "desc": "Long-wear dewy-finish cushion foundation from DD'ELL, manufactured by COSMEDIQUE Co., Ltd. Buildable coverage, hydrating formula suitable for normal-to-dry skin. OEM/ODM-ready — custom shades and packaging available at MOQ 1,000 per SKU.",
      "img": "images/products/ddell-dewy-glow-cushion.jpg",
      "specs": [
        [
          "Brand",
          "DD'ELL"
        ],
        [
          "Category",
          "Makeup — Cushion Pact"
        ],
        [
          "Finish",
          "Dewy / Luminous"
        ],
        [
          "Retail MSRP",
          "USD 36"
        ],
        [
          "Manufacturer",
          "COSMEDIQUE Co., Ltd."
        ]
      ],
      "features": [
        "Dewy luminous finish — ideal for normal-to-dry skin",
        "Hydrating formula with buildable coverage",
        "OEM/ODM custom shade and packaging available",
        "Korean-manufactured under COSMEDIQUE since 1985"
      ],
      "tags": [
        "retail",
        "hospitality"
      ],
      "scale": [
        "m",
        "l"
      ],
      "moq": 1000,
      "leadMin": 4,
      "leadMax": 6,
      "maker": "COSMEDIQUE Co., Ltd.",
      "cardTag": "DD'ELL · Cushion",
      "matchDesc": "Dewy-finish cushion foundation · DD'ELL · MOQ 1,000"
    },
    {
      "id": "ddell-line-lift-cushion",
      "sector": "k-beauty",
      "model": "LINE LIFT CUSHION PACT",
      "part": "DDELL-CUSH-LL (PRD-954)",
      "sub": "DD'ELL · Lifting cushion with firming peptide complex",
      "desc": "Firming line-lift cushion foundation from DD'ELL. Combines peptide complex with buildable coverage for a sculpted, age-defying finish. Manufactured by COSMEDIQUE Co., Ltd. under Korean cosmetic safety standards (CGMP).",
      "img": "images/products/ddell-line-lift-cushion.jpg",
      "specs": [
        [
          "Brand",
          "DD'ELL"
        ],
        [
          "Category",
          "Makeup — Cushion Pact"
        ],
        [
          "Finish",
          "Semi-matte / Lifting"
        ],
        [
          "Retail MSRP",
          "USD 36"
        ],
        [
          "Manufacturer",
          "COSMEDIQUE Co., Ltd."
        ]
      ],
      "features": [
        "Peptide-enhanced lifting formula",
        "Buildable coverage with semi-matte finish",
        "CGMP-compliant Korean manufacturing",
        "OEM/ODM private-label ready at MOQ 1,000"
      ],
      "tags": [
        "retail",
        "hospitality"
      ],
      "scale": [
        "m",
        "l"
      ],
      "moq": 1000,
      "leadMin": 4,
      "leadMax": 6,
      "maker": "COSMEDIQUE Co., Ltd.",
      "cardTag": "DD'ELL · Anti-Age",
      "matchDesc": "Peptide line-lift cushion · DD'ELL · MOQ 1,000"
    },
    {
      "id": "ddell-filter-primer-zeropore",
      "sector": "k-beauty",
      "model": "FILTER PRIMER ZEROPORE",
      "part": "DDELL-PRIM-ZP (PRD-964)",
      "sub": "DD'ELL · Pore-blurring primer with smoothing silicone matrix",
      "desc": "Makeup primer designed to blur pores and create a smooth canvas for foundation. Silicone-based matrix delivers immediate pore-filling effect. From DD'ELL, made by COSMEDIQUE Co., Ltd.",
      "img": "images/products/ddell-filter-primer-zeropore.jpg",
      "specs": [
        [
          "Brand",
          "DD'ELL"
        ],
        [
          "Category",
          "Makeup — Primer / Base"
        ],
        [
          "Texture",
          "Silicone gel-cream"
        ],
        [
          "Retail MSRP",
          "USD 26"
        ],
        [
          "Manufacturer",
          "COSMEDIQUE Co., Ltd."
        ]
      ],
      "features": [
        "Instant pore-blurring optical effect",
        "Silicone matrix for smooth foundation application",
        "Oil-control for long-wear makeup",
        "OEM/ODM-ready at MOQ 1,000 per SKU"
      ],
      "tags": [
        "retail",
        "hospitality"
      ],
      "scale": [
        "m",
        "l"
      ],
      "moq": 1000,
      "leadMin": 4,
      "leadMax": 6,
      "maker": "COSMEDIQUE Co., Ltd.",
      "cardTag": "DD'ELL · Primer",
      "matchDesc": "Pore-blurring makeup primer · DD'ELL · MOQ 1,000"
    },
    {
      "id": "ddell-setup-creame",
      "sector": "k-beauty",
      "model": "SETUP CREAME",
      "part": "DDELL-CRM-SU (PRD-956)",
      "sub": "DD'ELL · Hydrating makeup-base cream for lasting wear",
      "desc": "Rich hydrating cream designed as a makeup base — locks moisture, improves foundation adhesion, and extends wear time. Manufactured by COSMEDIQUE Co., Ltd. under Korean CGMP standards.",
      "img": "images/products/ddell-setup-creame.jpg",
      "specs": [
        [
          "Brand",
          "DD'ELL"
        ],
        [
          "Category",
          "Makeup Base / Moisturizer"
        ],
        [
          "Texture",
          "Rich cream"
        ],
        [
          "Retail MSRP",
          "USD 28"
        ],
        [
          "Manufacturer",
          "COSMEDIQUE Co., Ltd."
        ]
      ],
      "features": [
        "Deep hydration — improves foundation adhesion",
        "Extends long-wear performance of makeup",
        "Suitable for normal-to-dry skin",
        "OEM/ODM customisation at MOQ 1,000"
      ],
      "tags": [
        "retail",
        "hospitality"
      ],
      "scale": [
        "m",
        "l"
      ],
      "moq": 1000,
      "leadMin": 4,
      "leadMax": 6,
      "maker": "COSMEDIQUE Co., Ltd.",
      "cardTag": "DD'ELL · Base",
      "matchDesc": "Hydrating makeup-base cream · DD'ELL · MOQ 1,000"
    },
    {
      "id": "ddell-glowup-cream",
      "sector": "k-beauty",
      "model": "GLOWUP CREAM",
      "part": "DDELL-CRM-GU (PRD-958)",
      "sub": "DD'ELL · Radiance-boosting cream with luminous pigment complex",
      "desc": "Daily-wear radiance cream from DD'ELL that delivers an immediate luminous finish. Blends skincare hydration with a subtle light-reflecting pigment complex for a healthy-glow look, on its own or under makeup.",
      "img": "images/products/ddell-glowup-cream.jpg",
      "specs": [
        [
          "Brand",
          "DD'ELL"
        ],
        [
          "Category",
          "Skincare / Glow Cream"
        ],
        [
          "Texture",
          "Lightweight cream"
        ],
        [
          "Retail MSRP",
          "USD 28"
        ],
        [
          "Manufacturer",
          "COSMEDIQUE Co., Ltd."
        ]
      ],
      "features": [
        "Light-reflecting radiance complex",
        "Hydration + subtle luminous finish in one step",
        "Works solo or as makeup primer",
        "OEM/ODM-ready with private-label packaging"
      ],
      "tags": [
        "retail",
        "hospitality"
      ],
      "scale": [
        "m",
        "l"
      ],
      "moq": 1000,
      "leadMin": 4,
      "leadMax": 6,
      "maker": "COSMEDIQUE Co., Ltd.",
      "cardTag": "DD'ELL · Skincare",
      "matchDesc": "Luminous radiance cream · DD'ELL · MOQ 1,000"
    },
    {
      "id": "ddell-mask-defense",
      "sector": "k-beauty",
      "model": "MAKEUP FIXER MASK DEFENSE",
      "part": "DDELL-FIX-MD (PRD-961)",
      "sub": "DD'ELL · Setting mist engineered for mask-on makeup wear",
      "desc": "Setting mist specifically formulated to keep makeup intact under face masks. Quick-drying, non-sticky finish — prevents transfer and oxidation during extended wear. From DD'ELL, by COSMEDIQUE Co., Ltd.",
      "img": "images/products/ddell-mask-defense.jpg",
      "specs": [
        [
          "Brand",
          "DD'ELL"
        ],
        [
          "Category",
          "Makeup Fixer / Setting Mist"
        ],
        [
          "Format",
          "Pump mist spray"
        ],
        [
          "Retail MSRP",
          "USD 16"
        ],
        [
          "Manufacturer",
          "COSMEDIQUE Co., Ltd."
        ]
      ],
      "features": [
        "Mask-proof makeup lock technology",
        "Non-sticky, quick-dry finish",
        "Anti-transfer and anti-oxidation",
        "OEM/ODM with private-label fragrance options"
      ],
      "tags": [
        "retail",
        "hospitality"
      ],
      "scale": [
        "m",
        "l"
      ],
      "moq": 1000,
      "leadMin": 4,
      "leadMax": 6,
      "maker": "COSMEDIQUE Co., Ltd.",
      "cardTag": "DD'ELL · Fixer",
      "matchDesc": "Mask-proof setting mist · DD'ELL · MOQ 1,000"
    },
    {
      "id": "ddell-fixer-dewy-glow",
      "sector": "k-beauty",
      "model": "MAKEUP FIXER DEWY GLOW",
      "part": "DDELL-FIX-DG (PRD-959)",
      "sub": "DD'ELL · Setting mist that locks in a dewy, luminous finish",
      "desc": "Setting mist from DD'ELL that finishes makeup with a dewy, hydrated glow. Fine-atomising pump delivers an even micro-mist with no alcohol drag. Made by COSMEDIQUE Co., Ltd. in Seoul.",
      "img": "images/products/ddell-fixer-dewy-glow.jpg",
      "specs": [
        [
          "Brand",
          "DD'ELL"
        ],
        [
          "Category",
          "Makeup Fixer / Setting Mist"
        ],
        [
          "Finish",
          "Dewy / Luminous"
        ],
        [
          "Retail MSRP",
          "USD 16"
        ],
        [
          "Manufacturer",
          "COSMEDIQUE Co., Ltd."
        ]
      ],
      "features": [
        "Locks in a dewy glow finish",
        "Alcohol-free formulation — no tight-feel",
        "Fine micro-mist atomiser",
        "OEM/ODM options for volume and scent"
      ],
      "tags": [
        "retail",
        "hospitality"
      ],
      "scale": [
        "m",
        "l"
      ],
      "moq": 1000,
      "leadMin": 4,
      "leadMax": 6,
      "maker": "COSMEDIQUE Co., Ltd.",
      "cardTag": "DD'ELL · Fixer",
      "matchDesc": "Dewy-glow setting mist · DD'ELL · MOQ 1,000"
    },
    {
      "id": "ddell-egf-ampoule",
      "sector": "k-beauty",
      "model": "E.G.F AMPOULE",
      "part": "DDELL-AMP-EGF (PRD-909)",
      "sub": "DD'ELL · Epidermal Growth Factor ampoule for advanced skin repair",
      "desc": "High-concentration EGF (Epidermal Growth Factor) ampoule from DD'ELL. Targets cellular turnover, skin barrier repair, and fine-line reduction. Manufactured by COSMEDIQUE Co., Ltd. — a biomedical cosmetic specialist.",
      "img": "images/products/ddell-egf-ampoule.jpg",
      "specs": [
        [
          "Brand",
          "DD'ELL"
        ],
        [
          "Category",
          "Skincare / Advanced Ampoule"
        ],
        [
          "Key Actives",
          "Epidermal Growth Factor (EGF)"
        ],
        [
          "Retail MSRP",
          "USD 76"
        ],
        [
          "Manufacturer",
          "COSMEDIQUE Co., Ltd."
        ]
      ],
      "features": [
        "High-potency EGF for cellular renewal",
        "Barrier repair and fine-line reduction",
        "Dermatologically tested formulation",
        "OEM/ODM available with MOQ 1,000"
      ],
      "tags": [
        "retail",
        "healthcare",
        "hospitality"
      ],
      "scale": [
        "m",
        "l"
      ],
      "moq": 1000,
      "leadMin": 4,
      "leadMax": 6,
      "maker": "COSMEDIQUE Co., Ltd.",
      "cardTag": "DD'ELL · EGF",
      "matchDesc": "EGF repair ampoule · DD'ELL · MOQ 1,000"
    },
    {
      "id": "demed-vitamin-c-ampoule",
      "sector": "k-beauty",
      "model": "VITAMIN C AMPOULE",
      "part": "DEMED-AMP-VC (PRD-81)",
      "sub": "DEMED · Brightening ampoule with fast-absorbing Vitamin C",
      "desc": "Dermatological Vitamin C brightening ampoule from DEMED (est. 1985). 7ml × 5 ampoules format; fast-absorbing formula targets dull tone, pigmentation, and uneven texture. Manufactured by COSMEDIQUE Co., Ltd. under 39+ years of Korean cosmetic R&D.",
      "img": "images/products/demed-vitamin-c-ampoule.jpg",
      "specs": [
        [
          "Brand",
          "DEMED (est. 1985)"
        ],
        [
          "Category",
          "Dermatological Ampoule"
        ],
        [
          "Volume",
          "7 ml × 5 EA"
        ],
        [
          "Key Actives",
          "Vitamin C (Ascorbyl derivatives)"
        ],
        [
          "Retail MSRP",
          "USD 133.20"
        ],
        [
          "Manufacturer",
          "COSMEDIQUE Co., Ltd."
        ]
      ],
      "features": [
        "Brightening — targets dullness and pigmentation",
        "Fast-absorbing ampoule format for daily intensive care",
        "Sealed single-use vials preserve ingredient stability",
        "OEM/ODM available at MOQ 1,000 per SKU"
      ],
      "tags": [
        "retail",
        "healthcare",
        "hospitality"
      ],
      "scale": [
        "m",
        "l"
      ],
      "moq": 1000,
      "leadMin": 4,
      "leadMax": 6,
      "maker": "COSMEDIQUE Co., Ltd.",
      "cardTag": "DEMED · Ampoule",
      "matchDesc": "Vitamin C brightening ampoule · DEMED · MOQ 1,000"
    },
    {
      "id": "demed-collagen-ampoule-30ml",
      "sector": "k-beauty",
      "model": "COLLAGEN AMPOULE 30ML",
      "part": "DEMED-AMP-COL30 (PRD-65)",
      "sub": "DEMED · Firming collagen ampoule in 30 ml jumbo format",
      "desc": "High-concentration collagen ampoule in a generous 30 ml pump bottle — suitable for daily face + neck application. From DEMED (1985), a dermatological cosmetic brand manufactured by COSMEDIQUE Co., Ltd.",
      "img": "images/products/demed-collagen-ampoule-30ml.jpg",
      "specs": [
        [
          "Brand",
          "DEMED (est. 1985)"
        ],
        [
          "Category",
          "Dermatological Ampoule"
        ],
        [
          "Volume",
          "30 ml"
        ],
        [
          "Key Actives",
          "Hydrolysed collagen peptides"
        ],
        [
          "Retail MSRP",
          "USD 57.72"
        ],
        [
          "Manufacturer",
          "COSMEDIQUE Co., Ltd."
        ]
      ],
      "features": [
        "Firming and elasticity support via collagen peptides",
        "Large 30 ml format — daily face + neck use",
        "Lightweight, fast-absorbing texture",
        "OEM/ODM-ready with custom packaging"
      ],
      "tags": [
        "retail",
        "healthcare",
        "hospitality"
      ],
      "scale": [
        "m",
        "l"
      ],
      "moq": 1000,
      "leadMin": 4,
      "leadMax": 6,
      "maker": "COSMEDIQUE Co., Ltd.",
      "cardTag": "DEMED · Collagen",
      "matchDesc": "Collagen firming ampoule 30 ml · DEMED · MOQ 1,000"
    },
    {
      "id": "demed-collagen-ampoule-7ml",
      "sector": "k-beauty",
      "model": "COLLAGEN AMPOULE 7ML × 5EA",
      "part": "DEMED-AMP-COL5 (PRD-82)",
      "sub": "DEMED · Collagen ampoule in single-use vial 5-pack",
      "desc": "5-pack of single-use 7 ml collagen ampoules for intensive weekly treatment. Sealed vials preserve peptide integrity. Manufactured by COSMEDIQUE Co., Ltd. — premium dermatological cosmetics since 1985.",
      "img": "images/products/demed-collagen-ampoule-7ml.jpg",
      "specs": [
        [
          "Brand",
          "DEMED (est. 1985)"
        ],
        [
          "Category",
          "Dermatological Ampoule"
        ],
        [
          "Volume",
          "7 ml × 5 EA"
        ],
        [
          "Key Actives",
          "Hydrolysed collagen peptides"
        ],
        [
          "Retail MSRP",
          "USD 133.20"
        ],
        [
          "Manufacturer",
          "COSMEDIQUE Co., Ltd."
        ]
      ],
      "features": [
        "Intensive single-use 5-pack treatment",
        "Sealed vials preserve peptide freshness",
        "Firming and elasticity support",
        "OEM/ODM with private-label vial branding"
      ],
      "tags": [
        "retail",
        "healthcare",
        "hospitality"
      ],
      "scale": [
        "m",
        "l"
      ],
      "moq": 1000,
      "leadMin": 4,
      "leadMax": 6,
      "maker": "COSMEDIQUE Co., Ltd.",
      "cardTag": "DEMED · Collagen",
      "matchDesc": "Collagen ampoule 7 ml × 5 · DEMED · MOQ 1,000"
    },
    {
      "id": "demed-hyaluronic-soothing-ampoule",
      "sector": "k-beauty",
      "model": "HYALURONIC SOOTHING AMPOULE",
      "part": "DEMED-AMP-HYA (PRD-60)",
      "sub": "DEMED · Multi-weight hyaluronic soothing ampoule, 7 ml × 5",
      "desc": "Soothing ampoule featuring multi-molecular-weight hyaluronic acid for layered hydration. Calms sensitised skin while restoring moisture barrier. From DEMED by COSMEDIQUE Co., Ltd.",
      "img": "images/products/demed-hyaluronic-soothing-ampoule.jpg",
      "specs": [
        [
          "Brand",
          "DEMED (est. 1985)"
        ],
        [
          "Category",
          "Dermatological Ampoule"
        ],
        [
          "Volume",
          "7 ml × 5 EA"
        ],
        [
          "Key Actives",
          "Multi-weight Hyaluronic Acid"
        ],
        [
          "Retail MSRP",
          "USD 125.80"
        ],
        [
          "Manufacturer",
          "COSMEDIQUE Co., Ltd."
        ]
      ],
      "features": [
        "Layered hydration with multi-weight HA",
        "Soothing for sensitised and post-procedure skin",
        "Moisture-barrier repair",
        "OEM/ODM-ready at MOQ 1,000"
      ],
      "tags": [
        "retail",
        "healthcare",
        "hospitality"
      ],
      "scale": [
        "m",
        "l"
      ],
      "moq": 1000,
      "leadMin": 4,
      "leadMax": 6,
      "maker": "COSMEDIQUE Co., Ltd.",
      "cardTag": "DEMED · Hydration",
      "matchDesc": "Hyaluronic soothing ampoule · DEMED · MOQ 1,000"
    },
    {
      "id": "demed-brightening-ampoule",
      "sector": "k-beauty",
      "model": "BRIGHTENING AMPOULE",
      "part": "DEMED-AMP-BRT (PRD-61)",
      "sub": "DEMED · Intensive brightening ampoule, 7 ml × 5",
      "desc": "Intensive brightening ampoule targeting uneven tone, melanin over-production, and post-inflammatory pigmentation. 5 single-use vials for concentrated weekly treatment. From DEMED, manufactured by COSMEDIQUE Co., Ltd.",
      "img": "images/products/demed-brightening-ampoule.jpg",
      "specs": [
        [
          "Brand",
          "DEMED (est. 1985)"
        ],
        [
          "Category",
          "Dermatological Ampoule"
        ],
        [
          "Volume",
          "7 ml × 5 EA"
        ],
        [
          "Key Actives",
          "Niacinamide + Vitamin C complex"
        ],
        [
          "Retail MSRP",
          "USD 133.20"
        ],
        [
          "Manufacturer",
          "COSMEDIQUE Co., Ltd."
        ]
      ],
      "features": [
        "Targets melanin over-production and PIH",
        "Intensive 5-pack weekly treatment",
        "Sealed vials preserve active stability",
        "OEM/ODM with custom active concentrations"
      ],
      "tags": [
        "retail",
        "healthcare",
        "hospitality"
      ],
      "scale": [
        "m",
        "l"
      ],
      "moq": 1000,
      "leadMin": 4,
      "leadMax": 6,
      "maker": "COSMEDIQUE Co., Ltd.",
      "cardTag": "DEMED · Brightening",
      "matchDesc": "Brightening ampoule · DEMED · MOQ 1,000"
    },
    {
      "id": "demed-spicule-peptide-300",
      "sector": "k-beauty",
      "model": "SPICULE PEPTIDE 300 SHOT",
      "part": "DEMED-AMP-SP300 (PRD-59)",
      "sub": "DEMED · Spicule-delivery peptide shot ampoule, 7 ml × 5",
      "desc": "Advanced spicule-technology ampoule from DEMED. Marine spicules create micro-channels that drive peptide actives deeper into the skin — clinical-grade home-care targeting fine lines and texture. Made by COSMEDIQUE Co., Ltd.",
      "img": "images/products/demed-spicule-peptide-300.jpg",
      "specs": [
        [
          "Brand",
          "DEMED (est. 1985)"
        ],
        [
          "Category",
          "Advanced Dermatological Ampoule"
        ],
        [
          "Volume",
          "7 ml × 5 EA"
        ],
        [
          "Technology",
          "Marine spicule delivery + peptides"
        ],
        [
          "Retail MSRP",
          "USD 125.80"
        ],
        [
          "Manufacturer",
          "COSMEDIQUE Co., Ltd."
        ]
      ],
      "features": [
        "Marine spicule micro-channel delivery",
        "Deep-penetration peptide complex",
        "Clinical-grade home-care formulation",
        "OEM/ODM technology licensing available"
      ],
      "tags": [
        "retail",
        "healthcare",
        "hospitality"
      ],
      "scale": [
        "m",
        "l"
      ],
      "moq": 1000,
      "leadMin": 4,
      "leadMax": 6,
      "maker": "COSMEDIQUE Co., Ltd.",
      "cardTag": "DEMED · Spicule",
      "matchDesc": "Spicule peptide 300 shot · DEMED · MOQ 1,000"
    },
    {
      "id": "demed-extra-intense-moisture-cream-m8",
      "sector": "k-beauty",
      "model": "EXTRA INTENSE MOISTURE CREAM 50G [M8]",
      "part": "DEMED-CRM-M8 (PRD-71)",
      "sub": "DEMED · Barrier-repair cream for very dry / compromised skin",
      "desc": "Extra-rich moisture cream from DEMED's dermatological M-series. Targets very dry, dehydrated, or post-procedure skin with barrier-repair ceramides and occlusives. 50g jar. Manufactured by COSMEDIQUE Co., Ltd.",
      "img": "images/products/demed-extra-intense-moisture-cream-m8.jpg",
      "specs": [
        [
          "Brand",
          "DEMED (est. 1985)"
        ],
        [
          "Category",
          "Dermatological Moisture Cream"
        ],
        [
          "Volume",
          "50 g"
        ],
        [
          "Series",
          "M-series [M8]"
        ],
        [
          "Retail MSRP",
          "USD 72.52"
        ],
        [
          "Manufacturer",
          "COSMEDIQUE Co., Ltd."
        ]
      ],
      "features": [
        "Intensive barrier-repair formulation",
        "Ceramide + occlusive complex for very dry skin",
        "Suitable for post-procedure / compromised skin",
        "OEM/ODM formulation tiers M1–M8 available"
      ],
      "tags": [
        "retail",
        "healthcare",
        "hospitality"
      ],
      "scale": [
        "m",
        "l"
      ],
      "moq": 1000,
      "leadMin": 4,
      "leadMax": 6,
      "maker": "COSMEDIQUE Co., Ltd.",
      "cardTag": "DEMED · Barrier Cream",
      "matchDesc": "Barrier-repair moisture cream · DEMED · MOQ 1,000"
    },
    {
      "id": "demed-wonder-ceramid-toner",
      "sector": "k-beauty",
      "model": "WONDER CERAMID TONER",
      "part": "DEMED-TNR-WC (PRD-92)",
      "sub": "DEMED · New-release ceramide toner for barrier support",
      "desc": "Recently-released ceramide-rich toner from DEMED. First-step hydration that primes the barrier for subsequent actives. Dermatologically formulated, manufactured by COSMEDIQUE Co., Ltd. under CGMP Korean standards.",
      "img": "images/products/demed-wonder-ceramid-toner.jpg",
      "specs": [
        [
          "Brand",
          "DEMED (est. 1985)"
        ],
        [
          "Category",
          "Dermatological Toner"
        ],
        [
          "Key Actives",
          "Ceramide NP complex"
        ],
        [
          "Release",
          "2024 New Release"
        ],
        [
          "Manufacturer",
          "COSMEDIQUE Co., Ltd."
        ]
      ],
      "features": [
        "Ceramide-forward barrier support",
        "First-step hydration layer",
        "Primes skin for subsequent ampoules / creams",
        "OEM/ODM-ready with custom fragrance / pH"
      ],
      "tags": [
        "retail",
        "healthcare",
        "hospitality"
      ],
      "scale": [
        "m",
        "l"
      ],
      "moq": 1000,
      "leadMin": 4,
      "leadMax": 6,
      "maker": "COSMEDIQUE Co., Ltd.",
      "cardTag": "DEMED · New",
      "matchDesc": "Ceramide barrier toner · DEMED · MOQ 1,000"
    }
  ],
  "k-tourism-assets": [
    {
      "id": "hanok-sopunghun",
      "sector": "k-tourism-assets",
      "model": "Sopunghun",
      "part": "YSH-SPH-25 (3 identical units · Rooms 1 · 2 · 3)",
      "sub": "Classic Hanok Stay · 25-pyeong (~83 m²)",
      "desc": "25-pyeong traditional stand-alone hanok unit at Yangpyeong Soohyang The Hanok — accommodates 4 standard / 6 max guests. Each unit features a hinoki cypress room, full kitchen, and free WiFi. Three identical units available (Rooms 1·2·3). Annual gujwa-bunyang fractional share ownership program offered to long-term investors.",
      "specs": [
        [
          "Floor Area",
          "25 pyeong (~83 m²)"
        ],
        [
          "Capacity",
          "4 standard / 6 max"
        ],
        [
          "Units",
          "3 identical (Rooms 1·2·3)"
        ],
        [
          "Amenities",
          "Hinoki cypress room · Full kitchen · Free WiFi"
        ],
        [
          "Location",
          "Yangpyeong, Gyeonggi-do"
        ],
        [
          "Share Program",
          "Annual gujwa-bunyang fractional share"
        ]
      ],
      "features": [
        "Stand-alone 25-pyeong traditional hanok unit",
        "Hinoki cypress bath room and full kitchen",
        "Three identical units operable independently",
        "Annual fractional share (gujwa-bunyang) ownership available"
      ],
      "tags": [
        "hospitality"
      ],
      "scale": [
        "m",
        "l"
      ],
      "maker": "Yangpyeong Soohyang The Hanok",
      "cardTag": "Classic Hanok Stay · 25-pyeong",
      "matchDesc": "Classic 25-pyeong hanok unit · Yangpyeong · 4 std / 6 max · annual share"
    },
    {
      "id": "hanok-soyojae",
      "sector": "k-tourism-assets",
      "model": "Soyojae",
      "part": "YSH-SYJ-30 (3 identical units · Rooms 1 · 2 · 3)",
      "sub": "Premium Hanok Stay · 30-pyeong (~99 m²)",
      "desc": "30-pyeong premium stand-alone hanok unit at Yangpyeong Soohyang The Hanok — accommodates 4 standard / 8 max guests. Larger footprint with hinoki cypress room, full kitchen, and free WiFi. Three identical units available (Rooms 1·2·3). Annual gujwa-bunyang fractional share ownership program offered.",
      "specs": [
        [
          "Floor Area",
          "30 pyeong (~99 m²)"
        ],
        [
          "Capacity",
          "4 standard / 8 max"
        ],
        [
          "Units",
          "3 identical (Rooms 1·2·3)"
        ],
        [
          "Amenities",
          "Hinoki cypress room · Full kitchen · Free WiFi"
        ],
        [
          "Location",
          "Yangpyeong, Gyeonggi-do"
        ],
        [
          "Share Program",
          "Annual gujwa-bunyang fractional share"
        ]
      ],
      "features": [
        "Premium 30-pyeong stand-alone hanok with larger footprint",
        "Hinoki cypress bath room and full kitchen",
        "Three identical units operable independently",
        "Annual fractional share (gujwa-bunyang) ownership available"
      ],
      "tags": [
        "hospitality"
      ],
      "scale": [
        "m",
        "l"
      ],
      "maker": "Yangpyeong Soohyang The Hanok",
      "cardTag": "Premium Hanok Stay · 30-pyeong",
      "matchDesc": "Premium 30-pyeong hanok unit · Yangpyeong · 4 std / 8 max · annual share"
    },
    {
      "id": "hanok-gyeonwujae",
      "sector": "k-tourism-assets",
      "model": "Gyeonwujae",
      "part": "YSH-GWJ-25P (2 identical units · Rooms 1 · 2)",
      "sub": "Pet-Friendly Hanok · 25-pyeong (~83 m²)",
      "desc": "25-pyeong pet-friendly stand-alone hanok unit at Yangpyeong Soohyang The Hanok — dogs welcome. Accommodates 4 standard / 6 max guests with hinoki cypress room, full kitchen, and free WiFi. Two identical units available (Rooms 1·2). Annual gujwa-bunyang fractional share ownership program offered.",
      "specs": [
        [
          "Floor Area",
          "25 pyeong (~83 m²)"
        ],
        [
          "Capacity",
          "4 standard / 6 max"
        ],
        [
          "Units",
          "2 identical (Rooms 1·2)"
        ],
        [
          "Pet Policy",
          "Dogs welcome"
        ],
        [
          "Location",
          "Yangpyeong, Gyeonggi-do"
        ],
        [
          "Share Program",
          "Annual gujwa-bunyang fractional share"
        ]
      ],
      "features": [
        "Pet-friendly 25-pyeong stand-alone hanok (dogs welcome)",
        "Hinoki cypress bath room and full kitchen",
        "Two identical units operable independently",
        "Annual fractional share (gujwa-bunyang) ownership available"
      ],
      "tags": [
        "hospitality"
      ],
      "scale": [
        "m",
        "l"
      ],
      "maker": "Yangpyeong Soohyang The Hanok",
      "cardTag": "Pet-Friendly Hanok · 25-pyeong",
      "matchDesc": "Pet-friendly 25-pyeong hanok · Yangpyeong · 4 std / 6 max · dogs welcome"
    },
    {
      "id": "hanok-punggyeonru",
      "sector": "k-tourism-assets",
      "model": "Punggyeonru",
      "part": "YSH-PGR-30P (3 identical units · Rooms 1 · 2 · 3)",
      "sub": "Premium Pet-Friendly Hanok · 30-pyeong (~99 m²)",
      "desc": "30-pyeong premium pet-friendly stand-alone hanok unit at Yangpyeong Soohyang The Hanok — dogs welcome. Accommodates 4 standard / 8 max guests with hinoki cypress room, full kitchen, and free WiFi. Three identical units available (Rooms 1·2·3). Annual gujwa-bunyang fractional share ownership program offered.",
      "specs": [
        [
          "Floor Area",
          "30 pyeong (~99 m²)"
        ],
        [
          "Capacity",
          "4 standard / 8 max"
        ],
        [
          "Units",
          "3 identical (Rooms 1·2·3)"
        ],
        [
          "Pet Policy",
          "Dogs welcome"
        ],
        [
          "Location",
          "Yangpyeong, Gyeonggi-do"
        ],
        [
          "Share Program",
          "Annual gujwa-bunyang fractional share"
        ]
      ],
      "features": [
        "Premium pet-friendly 30-pyeong stand-alone hanok (dogs welcome)",
        "Hinoki cypress bath room and full kitchen",
        "Three identical units operable independently",
        "Annual fractional share (gujwa-bunyang) ownership available"
      ],
      "tags": [
        "hospitality"
      ],
      "scale": [
        "m",
        "l"
      ],
      "maker": "Yangpyeong Soohyang The Hanok",
      "cardTag": "Premium Pet-Friendly · 30-pyeong",
      "matchDesc": "Premium pet-friendly 30-pyeong hanok · Yangpyeong · 4 std / 8 max · dogs welcome"
    }
  ]
};
  var SECTOR_GRID = {
    "k-security":       "productGrid",
    "k-tech":           "ktechGrid",
    "k-energy":         "kenergyGrid",
    "k-bio":            "kbioGrid",
    "k-beauty":         "kbeautyGrid",
    "k-tourism-assets": "ktourismGrid"
  };

  /* Merge into the lexical `P` binding declared in index.html (const P at
     script scope is shared across classic scripts via the global lexical
     environment, but NOT exposed on window). `typeof` is safe on undeclared
     identifiers, so the guard works on pages without an inline P. */
  try {
    if (typeof P !== "undefined" && P && typeof P === "object") {
      Object.keys(ADDITIONS).forEach(function (id) {
        if (!P[id]) P[id] = ADDITIONS[id];
      });
    }
  } catch (_) {}
  try {
    if (typeof MATCH_CATALOG !== "undefined" && Array.isArray(MATCH_CATALOG)) {
      MATCH_ADDITIONS.forEach(function (m) {
        if (!MATCH_CATALOG.some(function (x) { return x.id === m.id; })) {
          MATCH_CATALOG.push(m);
        }
      });
    }
  } catch (_) {}

  /* Also expose on window — standalone pages' chat-core.js reads window.P. */
  if (!window.P) window.P = {};
  Object.keys(ADDITIONS).forEach(function (id) {
    if (!window.P[id]) window.P[id] = ADDITIONS[id];
  });
  if (Array.isArray(window.MATCH_CATALOG)) {
    MATCH_ADDITIONS.forEach(function (m) {
      if (!window.MATCH_CATALOG.some(function (x) { return x.id === m.id; })) {
        window.MATCH_CATALOG.push(m);
      }
    });
  }

  /* Runtime card builder — mirrors index.html card markup byte-for-byte. */
  var cardHtmlFor = function cardHtmlFor(id, p, i) {
    /* Mirrors index.html's inline card markup so the style matches 1:1. */
    const tag  = (p.cardTag || p.sub || '').replace(/"/g, '&quot;');
    const mfg  = (p.maker || 'ERGSN CO., LTD.') + ' <span class="card-verified">\u2713 Verified Partner</span>';
    const miniSpecs = (p.specs || []).slice(0, 4)
      .map(([k, v]) => `<div><p class="spec-lbl">${k}</p><p class="spec-val">${v}</p></div>`)
      .join('');
    const imgBlock = p.img
      ? `<div class="card-image"><picture><source srcset="${p.img.replace(/\.jpg$|\.png$/, '.webp')}" type="image/webp"><img src="${p.img}" alt="ERGSN ${p.model}" loading="lazy"></picture></div>`
      : '';
    const cardHtml =
      `<div class="product-card reveal" style="--i:${i}" tabindex="0" data-model="${id}" onclick="openModal('${id}')" onkeydown="if(event.key==='Enter'&&event.target===this)openModal('${id}')">` +
        imgBlock +
        `<p class="card-tag">${tag}</p>` +
        `<p class="card-model">${p.model}</p>` +
        `<p class="card-part">Part No: ${p.part}</p>` +
        `<p class="card-mfg">${mfg}</p>` +
        `<p class="card-desc">${p.desc.split('. ')[0]}.</p>` +
        `<div class="card-specs">${miniSpecs}</div>` +
        `<div class="card-foot">` +
          `<span class="card-cta">View Full Specs</span>` +
          `<button class="compare-btn" type="button" aria-label="Add ${p.model} to compare" onclick="event.stopPropagation();toggleCompare('${id}',this)">` +
            `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"><path d="M6 12h12M12 6v12"/></svg>Compare` +
          `</button>` +
        `</div>` +
      `</div>`;
    return cardHtml;
  };

  function injectCards() {
    Object.keys(CARDS_BY_SECTOR).forEach(function (sector) {
      var gridId = SECTOR_GRID[sector];
      if (!gridId) return; /* sector not active — skip for now */
      var grid = document.getElementById(gridId);
      if (!grid) return;
      var existing = Array.prototype.map.call(grid.querySelectorAll(":scope > .product-card"), function (c) { return c.getAttribute("data-model"); });
      CARDS_BY_SECTOR[sector].forEach(function (p, i) {
        if (existing.indexOf(p.id) !== -1) return; /* already rendered inline */
        var tmp = document.createElement("div");
        tmp.innerHTML = cardHtmlFor(p.id, ADDITIONS[p.id], i);
        grid.appendChild(tmp.firstChild);
      });
    });
    /* Re-populate Featured grid now that catalog-injected sectors have cards. */
    if (typeof populateFeaturedGrid === "function") {
      try { populateFeaturedGrid(); } catch (_) {}
    }
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", injectCards);
  } else {
    injectCards();
  }
})();
